name: Deploy Production

on:
  pull_request:
    branches: [ "main" ]

jobs:

  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push docker image
        run: |
          IMAGE_TAG="$COMPONENT_NAME:v$VERSION$SUFFIX"
          docker build . --file Dockerfile --tag $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_HUB_CLIENT_NAME: ${{ secrets.DOCKER_HUB_CLIENT_NAME }}
          COMPONENT_NAME: wallet-driving-application
          VERSION: 2.0.0
