name: Release
on:
  push:
    branches:
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
jobs:
  release-local:
    name: release-local
    runs-on: ubuntu-latest
    environment: local
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build and Push docker image
        run: |
          PROJECT_NAME=$(jq -r '.name' package.json)
          VERSION=$(jq -r '.version' package.json)
          IMAGE_TAG="$PROJECT_NAME:v$VERSION"
          docker build . --file Dockerfile --tag $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_HUB_CLIENT_NAME: in2workspace
